### ISSUE TITLE
Investigate and fix python and C++ flags logging

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/TensorComprehensions#113]
right now the LOG_IF doesn't play nice when we consider user experience trying to do the cuda dump in python interpreter. THey normally can do 
```
env GLOG_logtostderr=1 python my_test.py -v
```
and but this is not friendly when people have to do the stuff in python interpreter. For this reason, I had added a separate flag dump_cuda and GlobalDebugInit from python was setting that flag. However, having LOG_IF necessitates that we set env variable and doesn't play nice with logging.

this should be fixed more properly.

**Comment by ftynse** [comment]
The simplest solution here is to ask for
`tc.GlobalDebugInit('--logtostderr=1', '--dump_cuda')`
instead of just
`tc.GlobalDebugInit('--dump_cuda')`

This will have a side effect of redirecting all debugs to stderr though.

I don't like the `GlobalDebugInit` approach.  It has hidden state (can only be called once) and is essentially irreversible.  All flags are actually global variables in C++, they can be written!  This needs some thread-safety measures, but is perfectly feasible:
```
tc.enableDebugOutput(True)  # internally calls a C++ function that does FLAGS_logtostderr=1
tc.enableDebugTcMapper(True) # same for FLAGS_debug_tc_mapper=1
options = tc.autotune(blah)  # actual call
tc.enableDebugTcMapper(False) # set FLAGS_debug_tc_mapper=0
tc.enableDebugCuda(True) # set FLAGS_debug_cuda=1
tc.run(blah, options)
tc.enableDebugOutput(False) 
```
and allows much finer-grain control than global options.

**Comment by prigoyal** [comment]
yeah, I do agree that the `tc.GlobalDebugInit` needs to have thread-safety measure. but a proper harness needs to be built out for this with context managers etc. however, this is something that I planned to think about more after the release and understand what's going on with our logging
