### ISSUE TITLE
Improved Layer Fusion Support

### ISSUE THREAD

**Issue by jwfromm** [facebookresearch/TensorComprehensions#132]
It seems like one of the huge benefits of a tool like TC is the ability to fuse layers and optimize the schedule jointly. There may be significant speed-ups from fusing all the layers of a full model and auto-scheduling for example. Unless I'm reading the docs wrong, the only way to currently do this fusion is to define an entire model in one TC language. However, since there are already many standard layers in tc.database, it would be much cleaner to define the model as a series of TC layers. This could be implemented by adding a fuse function that takes a list of individual languages and produces one large one that can then be optimized. If something like this feature already exists, adding a fusion tutorial to the docs would prevent other people like me from getting confused.

**Comment by prigoyal** [comment]
this seems similar to https://github.com/facebookresearch/TensorComprehensions/issues/56, is that what you meant as well ? :)

**Comment by jwfromm** [comment]
You're right, thats the same feature.

**Comment by ftynse** [comment]
I'd say we need to implement #56 as forced inlining.

@jwfromm Because TC engine essentially takes strings as input, you may be
able to achieve the desired behavior with some string manipulation on the
TC source. Please also note that scheduling everything together is not
necessarily beneficial. Beyond increasing the scheduling time
exponentially, it may produce kernels that perform worse: all operations
will have to share limited resources (registers, shared memory) reducing
overall occupancy.
