### ISSUE TITLE
Protobuf version mismatch from fresh install

### ISSUE THREAD

**Issue by trypag** [facebookresearch/TensorComprehensions#141]
- OS: Fedora 25
- How you installed TC (docker, conda, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 8.0
- Conda version (if using conda): 4.4.11

repro:
```
conda clean --all
conda create -y --name tc-install python=3.6
conda activate tc-install
conda install -y -c pytorch -c tensorcomp tensor_comprehensions

# compile whatever TC
> Proto version doesn't match. TC git version is: 8e112e9dccda62c30ef29208a827e783b9a7f156 and Proto version is: ea0c39dcede6850bd3e9553eee0d4f083681c314 .This proto might be incompatible with your TC binary and can break. Please autotune against the correct TC version.
```

**Comment by ftynse** [comment]
This is a warning, not an actual error.  Does the kernel run?

Your setup does not seem that clean as this message appears when the autotuner reads files from the previous runs.  Please check that you don't have `.cuda` and `.options` files in your working directory and/or in `/tmp`.

**Comment by trypag** [comment]
Ok I didn't think this could be related, that's surprising, thanks :) solved
I had cache files from the previous protobuf version

**Comment by ftynse** [comment]
Yes, this should be more explicit (tag @prigoyal )

**Comment by prigoyal** [comment]
@trypag yep, whenever we change the binaries, there are chances that the old mapping options cache that the autotuner saves as protobuf might not be compatible with the new ones. We throw such warnings in that case. 

However, I think we should explicitly display them as warnings. fixed in https://github.com/facebookresearch/TensorComprehensions/pull/143 :)

**Comment by ftynse** [comment]
thanks @prigoyal !
