### ISSUE TITLE
Multiply reduction not initializing with identity of reduction

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/TensorComprehensions#245]
A user reported this problem here https://tensorcomprehensions.slack.com/archives/C98GR4E10/p1522443828000045

The multiply reduction *=! doesn't seem to be working i.e. it doesn't init output with the identity of reduction * which should be 1. Here the output is all still 0.

**Comment by ftynse** [comment]
Reduction initialization works just fine.

**Comment by ftynse** [comment]
Given that the weight matrix contains only values `0.1`, the resulting value is
0.1^(N*C*H*W*KW*KW=0.1^(64*10*24*24*7*7) for the reported sizes, which is muuuuuch smaller than the smallest representable value in double (~10^-318), let alone float.  Given machine precision, our code correctly outputs 0 as the result of that operation modulo machine precision.

Note that with W1 filled with 1 instead of 0.1, the resulting tensor contains only 1s, as expected.

**Comment by prigoyal** [comment]
thanks. the initialization is correct as verified in the code https://github.com/facebookresearch/TensorComprehensions/blob/master/src/core/tc2halide.cc#L571

my guess is the machine precision as well. I would love to hear from the user what they think of this to make sure we are not missing some perspective. Thanks. :)
