### ISSUE TITLE
Determine whether a loop should be parallelized in CPU backend from ISL

### ISSUE THREAD

**Issue by wsmoses** [facebookresearch/TensorComprehensions#34]
ISL internally dictates if loops should be run serially, or may be run in parallel. Presently we are conservative and always run loops serially (for CPU). We ought use the information from ISL to set the CPU parallelization flag appropriately for each loop.

**Comment by prigoyal** [comment]
can you add some description for this @wsmoses ?

**Comment by prigoyal** [comment]
@wsmoses should this be assigned to you? if you have bandwidth to take a stab at it :)

**Comment by ftynse** [comment]
We discussed this yesterday with @skimo-openhub , it needs some isl work

**Comment by skimo-openhub** [comment]
@wsmoses, I've put some code in the `pr/coincident` branch of the `isl` submodule.
It exposes an `isl_ast_node_for_is_coincident`, which you can either call directly
using `isl_ast_node_for_is_coincident(node.get())` or through the C++ interface
as `node.for_is_coincident()`.  For the latter option, you need to configure with
`-DWITH_BINDINGS=1` as otherwise the C++ bindings do not get updated.
Let me know if this solves your problem.  If it does, I'll get these changes merged
into the `isl` submodule.

**Comment by wsmoses** [comment]
Working on integration now, but yes that pr/coincident change is needed.

**Comment by skimo-openhub** [comment]
On Mon, Mar 26, 2018 at 01:57:05PM +0000, William Moses wrote:
> Working on integration now, but yes that pr/coincident change is needed.

Is it also _sufficient_?

skimo

**Comment by wsmoses** [comment]
From the standpoint of ISL, yes it seems to be (had to integrate some scheduling into CPU first to properly test, and it indeed seems to work)!
